controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController


diff_drive_controller:
  ros__parameters:
    cmd_vel_timeout: 999.0
    left_wheel_names:  ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.264
    wheel_radius: 0.034

    # บังคับใช้ position feedback ชัดเจน
    position_feedback: true

    publish_rate: 50.0
    use_stamped_vel: false
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    odom_topic: "/odom"
    enable_odom_tf: true

